version: "3.9"

services:

  db:
    image: postgres:15
    container_name: simple_erp_db
    restart: always
    environment:
      POSTGRES_DB: tienda
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_pass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: simple_erp_app
    command: python manage.py runserver 0.0.0.0:8000
    # volumes:
    #   - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_NAME: tienda
      DB_USER: postgres
      DB_PASSWORD: my_pass
      DB_HOST: db
      DB_PORT: 5432